### ISSUE TITLE
Webserver panel file permissions

### ISSUE THREAD

**Issue by zvaehn** [bastianallgeier/kirbycms#129]
Hi Bastian,

i am unable to update any of my pages via the panel.
If i klick on the save Button the spinner in the right upper corner keeps spinning, but no changes are applied.

The page `.txt`-files are temporarily set to `777`.
My `content`-folder has `775`.

Are there any other folder/file permissions i have to set?

Best,
Sven

**Comment by lukasbestle** [comment]
Hi Sven,

This is the repository for the old Kirby version (v1). It is no longer maintained. If you are having this problem with the old version, please try updating to [v2](https://github.com/getkirby/). Otherwise please re-open this issue at the [new repo](https://github.com/getkirby/panel). Thanks!

**Comment by zvaehn** [comment]
D’oh!

I know but google brought up the wrong search result ;)

thanks


On 25. Juni 2015 at 15:08:40, Lukas Bestle (notifications@github.com) wrote:

Hi Sven,

This is the repository for the old Kirby version (v1). It is no longer maintained. If you are having this problem with the old version, please try updating to v2. Otherwise please re-open this issue at the new repo. Thanks!
